### ISSUE TITLE
Is this ready for production use package tracking

### ISSUE THREAD

**Issue by mw44118** [aheadley/packagetrack#3]
Hi, I see several forks.  I need to track package arrivals on USPS, UPS, and FedEx.

Does this thing work?  Which fork should I use?

**Comment by aheadley** [comment]
I realize this is 4 years old and nearly certainly not relevant to you anymore, but whatever.

No, this is just a thing I use for a crappy IRC bot and is not production ready. Last I checked my fork supported more carriers than the others but that was a long time ago so I don't know what the status is now.
